# Generated by Django 5.0 on 2023-12-06 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceModel",
            fields=[
                ("ModelId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ModelType",
                    models.CharField(
                        choices=[
                            ("AC", "Air Conditioner"),
                            ("Refrigerator", "Refrigerator"),
                            ("Light", "Light"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ModelNumber", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.CharField(max_length=255)),
                ("BillingAddress", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrolledDevice",
            fields=[
                ("DeviceId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ModelId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.devicemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnergyData",
            fields=[
                ("DataId", models.AutoField(primary_key=True, serialize=False)),
                ("Timestamp", models.DateTimeField()),
                ("Label", models.CharField(max_length=50)),
                ("Value", models.FloatField()),
                (
                    "DeviceId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.enrolleddevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceLocation",
            fields=[
                ("LocationID", models.AutoField(primary_key=True, serialize=False)),
                ("Address", models.CharField(max_length=255)),
                ("UnitNumber", models.CharField(max_length=50)),
                ("MoveInDate", models.DateField()),
                ("SquareFootage", models.IntegerField()),
                ("Bedrooms", models.IntegerField()),
                ("Occupants", models.IntegerField()),
                ("zip_code", models.CharField(max_length=10, unique=True)),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.customer"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="enrolleddevice",
            name="LocationId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.servicelocation"
            ),
        ),
        migrations.CreateModel(
            name="EnergyPrice",
            fields=[
                ("PriceId", models.AutoField(primary_key=True, serialize=False)),
                ("Timestamp", models.DateTimeField()),
                ("Price", models.FloatField()),
                (
                    "ZipCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.servicelocation",
                        to_field="zip_code",
                    ),
                ),
            ],
        ),
    ]
